# metadata specialised for each experiment
core:
  project_name: rae
  storage_dir: ${oc.env:PROJECT_ROOT}/storage
  version: ${version:}
  tags:
    - develop
    - semantic_horizon
    - stitching
    - multilingual
  name: null

defaults:
  - hydra: default
  - nn: vision
  - train: reconstruction
  - _self_ # as last argument to allow the override of parameters via this main config
#    Decomment this parameter to get parallel job running
#  - hydra/launcher: joblib
