_target_: rae.modules.rel_vae.VanillaRelVAE
latent_dim: 500
hidden_dims: null
activation: torch.nn.GELU
remove_encoder_last_activation: True

# Relative params
relative_attention:
  _target_: rae.modules.attention.RelativeAttention
  similarity_mode: inner
  values_mode: similarities
  normalization_mode: l2
  in_features: null
  hidden_features: null
  transform_elements: null
  self_attention_hidden_dim: null
  values_self_attention_nhead: null
  similarities_quantization_mode: null
  similarities_bin_size: null
  similarities_aggregation_mode: null
  similarities_aggregation_n_groups: null
  anchors_sampling_mode: null
  n_anchors_sampling_per_class: null
  output_normalization_mode: layernorm
