_target_: rae.modules.rel_vae.VanillaRelVAE
latent_dim: 256
hidden_dims: null

# Relative params
relative_attention:
  _target_: rae.modules.attention.MultiheadRelativeAttention
  in_features: ${nn.module.model.latent_dim}
  relative_attentions:
    - _target_: rae.modules.attention.RelativeAttention
      similarity_mode: inner
      values_mode: similarities
      normalization_mode: l2
      in_features: ${nn.module.model.latent_dim}
      hidden_features: null
      transform_elements: null
      self_attention_hidden_dim: null
      values_self_attention_nhead: null
      similarities_quantization_mode: null
      similarities_bin_size: null
      similarities_aggregation_mode: null
      similarities_aggregation_n_groups: null
      anchors_sampling_mode: null
      n_anchors_sampling_per_class: null
      output_normalization_mode: layernorm
#    - _target_: rae.modules.attention.RelativeAttention
#      similarity_mode: inner
#      values_mode: similarities
#      normalization_mode: l2
#      in_features: ${nn.module.model.latent_dim}
#      hidden_features: null
#      transform_elements: null
#      values_self_attention_nhead: null
#      similarities_quantization_mode: null
#      similarities_bin_size: null
#      similarities_aggregation_mode: null
#      similarities_aggregation_n_groups: null
#      anchors_sampling_mode: null
#      n_anchors_sampling_per_class: null
#      output_normalization_mode: l2
  subspace_pooling: sum
