_target_: rae.modules.relresnet.RelResNet50

input_size: 224
use_pretrained: True
finetune: False

# Relative params
hidden_features: 256
normalization_mode: l2
similarity_mode: basis_change
values_mode: similarities
