_target_: rae.modules.relresnet.RelResNet
resnet_size: 18

input_size: 224
use_pretrained: True
finetune: False
transform_resnet_features: True

# Relative params
hidden_features: 512
dropout_p: 0.5
normalization_mode: l2
similarity_mode: inner
values_mode: similarities
similarities_quantization_mode: differentiable_round
similarities_bin_size: 0.05
