_target_: rae.pl_modules.pl_gautoencoder.LightningAutoencoder

loss:
  _target_: rae.losses.vae_loss.VaeLoss
  variational_beta: 1

model:
  input_size: 32

defaults:
  - _self_
  - model: vae #  rae
