_target_: rae.pl_modules.pl_continual_gclassifier.LightningContinualClassifier

loss:
  _target_: torch.nn.modules.loss.CrossEntropyLoss

model:
  input_size: 32

replay:
  _target_: rae.modules.replay.ReplayBuffer
  max_size: 0
  substitute_p: 0.5
  anchors_p: 0.5

defaults:
  - _self_
  - model: rcnn
