_target_: rae.modules.relresnet.RelResNet
resnet_size: 18

input_size: 224
use_pretrained: True
finetune: False
transform_resnet_features: True

# Relative params
hidden_features: 512
dropout_p: 0.5
transform_elements:
  - "attention_keys"
  - "attention_queries"
normalization_mode: l2
similarity_mode: inner
values_mode: similarities
similarities_quantization_mode: differentiable_round
similarities_bin_size: 0.05
similarities_aggregation_mode: null
similarities_aggregation_n_groups: null
anchors_sampling_mode: stratified
n_anchors_sampling_per_class: 3
